sudo: false
language: ruby

script: bundle exec ruby spec/unicode_confusable_spec.rb

rvm:
- 2.5.1
- 2.4.4
- 2.3.7
- 2.2
- ruby-head
- jruby-head
- jruby-9.1.16.0

matrix:
  allow_failures:
    - rvm: 2.2
    - rvm: jruby-head
